repositories:
  - name: jetstack
    url: https://charts.jetstack.io

releases:
  - name: mychart
    chart: .
    namespace: mychart
    values:
      - ./values.yaml
    installed: true
    dependencies:
      - version: v1.10.0
        chart: jetstack/cert-manager
